version: '2'

volumes:
  storage-temp:

services:
  provider:
    image: openstf/stf-armv7l
    restart: unless-stopped
    environment:
      - DEBUG=adb*
    command: stf provider --name ${PROVIDER_NAME} --connect-sub tcp://${APP_IP}:7250 --connect-push tcp://${APP_IP}:7270 --storage-url http://${APP_IP}/ --public-ip ${PROVIDER_IP} --heartbeat-interval 10000 --screen-ws-url-pattern "ws://${APP_IP}/d/${PROVIDER_NAME}/<%= serial %>/<%= publicPort %>/" --adb-host adb --min-port 7400 --max-port 7700
    ports:
      - 7400-7700:7400-7700
    depends_on:
      - adb
      - storage-temp

  storage-temp:
    build: storage-temp/
    restart: unless-stopped
    volumes:
      - storage-temp:/app/data
    command: stf storage-temp --port 3000 --save-dir /app/data

  adb:
    image: gounthar/docker-adb:stretch
    restart: unless-stopped
    privileged: true
    volumes:
      - /dev/bus/usb:/dev/bus/usb
